FROM python:3.11-slim
WORKDIR /app
COPY fastapi-app/ .
RUN pip install fastapi uvicorn cryptography mysql-connector-python python-dotenv
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
