-- Create Inventory Items table to store user-selected products
CREATE TABLE inventory_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES products(id),
  -- user_id VARCHAR(255) NOT NULL, -- Add user ID column later
  climate_change_impact DECIMAL(10, 4), -- Store the calculated primary impact
  impact_unit VARCHAR(50),             -- Store the unit for the impact
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
  -- Add unique constraint for product_id (and user_id later) if needed
  -- UNIQUE (user_id, product_id)
);
