server:
  port: 8080

spring:
  application:
    name: carbonx-backend
  datasource:
    url: jdbc:h2:file:./data/carbonx;MODE=PostgreSQL;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  h2:
    console:
      enabled: true
      path: /h2-console

olca:
  # Base URL of the IPC bridge that forwards JSON-RPC calls to openLCA
  ipcBaseUrl: http://127.0.0.1:8081
  # Enable to use canned responses for testing without the IPC bridge
  mock: false

logging:
  level:
    root: INFO
    com.carbonx.lca: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

# Example Postgres override (application-prod.yml or env vars):
# spring.datasource.url=jdbc:postgresql://localhost:5432/carbonx
# spring.datasource.username=carbonx
# spring.datasource.password=changeme


