server:
  port: 8080

spring:
  application:
    name: carbonx-backend
  datasource:
    url: jdbc:h2:file:./data/carbonx;MODE=PostgreSQL;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  h2:
    console:
      enabled: true
      path: /h2-console

olca:
  # Base URL should match the port shown in openLCA's IPC Server window (usually 8080 or 8081)
  ipcBaseUrl: http://127.0.0.1:8081 # Or 8080 if that's what openLCA uses

  # --- PASTE THE IDs HERE ---
  methodId: "61966689-76aa-4b3b-94f1-81989199433f"
  impactCategoryId: "35ead5f0-fc9d-4afc-9f17-0f2a2fbffbd2"

  # Enable to use canned responses for testing without the IPC bridge
  mock: false

logging:
  level:
    root: INFO
    com.carbonx.lca: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

# Example Postgres override (application-prod.yml or env vars):
# spring.datasource.url=jdbc:postgresql://localhost:5432/carbonx
# spring.datasource.username=carbonx
# spring.datasource.password=changeme


